### ISSUE TITLE
AssertionError when Results Directory does not exist

### ISSUE THREAD

**Issue by sebimarkgraf** [facebookresearch/denoised_mdp#3]
When trying the code for the first time, the validation in the config throws an error due to the default path not existing.
```
Traceback (most recent call last):
  File "/home/sebbo/Projekte/denoised_mdp/main.py", line 48, in <module>
    from config import InstantiatedConfig, to_config_and_instantiate
  File "/home/sebbo/Projekte/denoised_mdp/config.py", line 227, in <module>
    cs.store(name='config', node=Config())
  File "<attrs generated init config.Config>", line 24, in __init__
  File "/home/sebbo/Projekte/denoised_mdp/config.py", line 80, in exists_path
    assert os.path.exists(value)
AssertionError
```

This could be made easier by automatically creating the directory when it does not exist.

**Comment by SsnL** [comment]
Added results directory at default path.
